title: dimagolomozy
email: dima.golomozy@gmail.com
description: >-
  Small blog about programming;
  Java, Python, Amazon Web Service (AWS), DevOps
  and more...
baseurl: ""
url: "http://dimagolomozy.github.io"
facebook_us false
plugins:
  - jekyll-gist
  - jekyll-seo-tag
